name: Build SukunaOS ISO
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y live-build squashfs-with-zstd xorriso debootstrap rsync

      - name: Build ISO
        run: |
          sudo chmod +x scripts/*.sh || true
          sudo bash scripts/build_iso.sh

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: sukunaos-iso
          path: live-build/*.iso
